[package]
name = "urdf-rs"
version = "0.4.2"
authors = ["Takashi Ogura <t.ogura@gmail.com>"]
description = "URDF parser using serde-xml-rs"
license = "Apache-2.0"
keywords = ["robotics", "robot", "ros", "urdf"]
categories = ["data-structures", "parsing"]
repository = "https://github.com/OTL/urdf-rs"
documentation = "http://docs.rs/urdf-rs"

[dependencies]
serde-xml-rs = { version = "0.2.1", git = "https://github.com/RReverser/serde-xml-rs" }
serde = "1.0"
serde_derive = "1.0"
RustyXML = "0.1.1"
regex = "0.1"
